name: terraform-apply
on:
  push:
    branches:
      - main
    paths:
      - "infra/**"
jobs:
  terraform-dev-apply:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: write
    defaults:
      run:
        shell: bash
        working-directory: infra/dev
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/oidc-admin-role
          aws-region: ap-northeast-1
      - name: version
        run: echo "version=$(cat ../.terraform-version)" >> "$GITHUB_ENV"
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.version }}
      - name: init
        run: terraform init
      - name: apply
        id: apply
        run: terraform apply -auto-approve -no-color
      - uses: actions/github-script@v7
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        with:
          script: |
            const output = `
              ### Terraform Apply

              Detect infra code changes. Executed terraform apply.
              Check result and close this issue if there is no problem.

              #### result \`${{ steps.apply.outcome }}\`

              <details><summary>Show Apply Result</summary>

              \`\`\`\n
              ${{ steps.apply.outputs.stdout }}
              \`\`\`

              </details>
            `
            const title = `Deploy at ${(new Date).toString()}`
            const masked = output.replaceAll(process.env.AWS_ACCOUNT_ID, '***')
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: masked,
              title,
            })
